version: "3.8"

services:
  rails_app:
    image: ghcr.io/neonwatty/test:latest
    container_name: meme_search_rails_app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@meme-search-db:5432/meme_search_production
    ports:
      - "3000:3000"
    depends_on:
      meme-search-db:
        condition: service_healthy
    volumes:
      - ./memes/:/rails/public/memes

  image_to_text_app:
    image: ghcr.io/neonwatty/test2:latest
    ports:
      - 8000:8000
    volumes:
      - ./memes/:/app/public/memes
      - ./data/image_to_text_app:/app/db
    container_name: meme_search_image_to_text_app
    deploy:
      resources:
        limits: # <-- roughly tested min memory for cpu usage
          memory: 12GB
        # reservations: # <-- uncomment for gpu usage
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]

  meme-search-db:
    image: pgvector/pgvector:pg17
    container_name: meme-search-db # note: must use - and not _ as ActiveRecord uses URI::RFC2396_Parser to parse database URLs
    volumes:
      - ./data/meme-search-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: meme_search_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
